# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # Required for conda environment activation

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        activate-environment: netcdf-cog-stac
        environment-file: conda-environment.yml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with unittest
      run: |
        python -m unittest
    - name: Check types with mypy
      run: |
        mypy netcdf_cog_stac
